name: Deploy Leptos site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown --toolchain nightly

      - name: Install cargo-leptos
        run: cargo install cargo-leptos

      - name: Build with Leptos (CSR)
        run: cargo +nightly leptos build --release --features=hydrate

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site
